### ISSUE TITLE
👩‍🌾 Action graph flaky tests on Windows

### ISSUE THREAD

**Issue by chapulina** [ros2/rcl#885] opened 2021-01-22 03:10 UTC
## Bug report

**Required Info:**

- Operating System:
  - Windows
- Installation type:
  - source (CI)
- Version or commit hash:
  - master
- DDS implementation:
  - default
- Client library (if applicable):
  - `rcl`

#### Steps to reproduce issue

Tests that failed on `nightly_win_rel`:

```
rcl_action.TestActionGraphMultiNodeFixture.test_action_get_names_and_types 
rcl_action.TestActionGraphMultiNodeFixture.action_client_init_maybe_fail
rcl_action.TestActionGraphMultiNodeFixture.test_action_get_server_names_and_types_by_node 
rcl_action.TestActionGraphMultiNodeFixture.get_names_and_types_maybe_fail 
rcl_action.TestActionGraphMultiNodeFixture.rcl_get_client_names_and_types_by_node_maybe_fail
```

Tests that failed on `nightly_win_rep`:

```
rcl_action.TestActionGraphMultiNodeFixture.test_action_get_names_and_types 
rcl_action.TestActionGraphMultiNodeFixture.test_action_get_server_names_and_types_by_node 
rcl_action.TestActionGraphMultiNodeFixture.test_action_get_client_names_and_types_by_node 
rcl_action.TestActionGraphMultiNodeFixture.rcl_get_client_names_and_types_by_node_maybe_fail 
rcl_action.TestActionGraphMultiNodeFixture.rcl_get_server_names_and_types_by_node_maybe_fail 
rcl_action.TestActionGraphMultiNodeFixture.get_names_and_types_maybe_fail
```

Many of the failures say:

`Unable to attain all required nodes`

Looking through the history of these tests, it looks like they're all flaky :snowflake: 

#### Expected behavior

All tests pass :smile: 

#### Actual behavior

Many tests fail :disappointed: 

#### Additional information

This may be related to https://github.com/ros2/rcl/issues/855.

---

https://github.com/osrf/buildfarmer/issues/145

**Comment by clalancette** [comment] 2021-02-09 16:45
This one is actually a duplicate of https://github.com/ros2/rmw_connext/issues/472, so I'm going to close it out.

**Closed by clalancette** 2021-02-09 16:45 UTC
Labels: Windows, tests
