### ISSUE TITLE
[YAML parser] Configurable maximum values during parsing 

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/rcl#244] opened 2018-05-29 16:52 UTC
This set of maximum values should be reevaluated: https://github.com/ros2/rcl/blob/5edf27b032cdaa324349bbdc02a9772eb4d9443b/rcl_yaml_param_parser/src/parser.c#L65-L71

**Comment by kekstee** [comment] 2019-06-05 07:46
I was just about to open an issue about this set of limits.

More specifically I easily hit the 128 byte string length on resource file paths which will look something like:
"sharepath(absolute) + some subfolder + filename"

Maybe the length limit for keys and values should be separated?
Is this limit on strings enforced anywhere else?

**Comment by jacobperron** [comment] 2019-06-07 20:33
We should making the maximum values for string size, number of nodes, and number of parameters configurable. Perhaps it makes sense to default all of them to "no limit" and users can configure a hard limit to avoid dynamic memory allocation.

**Comment by jdlangs** [comment] 2019-10-15 15:54
@jacobperron could you provide some thoughts on what you consider configurable? Can we get away with compile-time definitions or is something more complex needed?

**Comment by jacobperron** [comment] 2019-10-15 16:48
Compile-time definitions might be okay, but then I guess one would have to compile `rcl_yaml_param_parser` from source to change a value. This is inconvenient if you've installed ROS 2 binaries. It might be nice to have more flexibility and configure these parser parameters at runtime. For example, we could bootstrap parameter parsing by first parsing an optional YAML file containing the parser parameters.

It would be good to get other thoughts on the matter.

**Comment by clalancette** [comment] 2019-10-15 17:52
Before we go too much further, I took a quick look at the code to make sure I could say something intelligent.  If you look at the places that `MAX_STRING_SIZE` is used ([here](https://github.com/ros2/rcl/blob/master/rcl_yaml_param_parser/src/parser.c#L210), [here](https://github.com/ros2/rcl/blob/master/rcl_yaml_param_parser/src/parser.c#L1119), [here](https://github.com/ros2/rcl/blob/master/rcl_yaml_param_parser/src/parser.c#L1318), and [here](https://github.com/ros2/rcl/blob/master/rcl_yaml_param_parser/src/parser.c#L1429)), it doesn't actually prevent allocations from happening.  It really just bounds the size that they could potentially be.

Given that, it is unclear to me what the purpose of the bound is.  @anup-pem is the original author of the code that got merged as https://github.com/ros2/rcl/pull/235 .  @anup-pem , could you comment on the reasons why you added the `MAX_STRING_SIZE` like you did, and some of the consequences of increasing that value and/or removing it altogether?  Thanks in advance.

**Comment by jdlangs** [comment] 2019-10-16 20:17
Given the impeding Eloquent feature freeze, is there any quick fix we can get in that would be accepted, especially if it's considered a breaking change? It would be really unfortunate if we ended up being stuck with this regression for another whole release cycle.

**Comment by dirk-thomas** [comment] 2019-10-16 20:19
The planned freeze date for Eloquent is in two days. Given that there is not even a proposal at the moment I don't think it is realistic to expect any changes to land in time. (I anyone proves me wrong I am more than happy to see this improved.)

**Comment by clalancette** [comment] 2019-10-16 20:29
I will point out that simply increasing the size is something we can do after the Eloquent release, as it shouldn't be an API or ABI break.  I'd still like to hear from @anup-pem about the reasons for the original limitation and downsides to increasing it before making a decision here.

**Comment by jdlangs** [comment] 2019-10-16 20:40
My proposal for a quick fix is to compile out the bounds check unless a compile definition is provided. Anyone relying on this bounding behavior (which I suspect is very few people) can build `rcl_yaml_param_parser` instead of using prebuilt binaries until a more comprehensive runtime configuration option can be proposed/designed.

**Comment by jdlangs** [comment] 2019-10-17 23:22
Since no one spoke up against the compile definition idea, I've created a minimal [PR](#521) for evaluation that implements the proposal.

**Comment by jacobperron** [comment] 2019-10-18 00:18
I skimmed through the original PR and this is the the only discussion I can find regarding the maximum values: https://github.com/ros2/rcl/pull/235#discussion_r186884689

> Don't have a great reason. Wanted to put a MAX value instead of having infinity.

It's not clear to me why we need any of these max values. If a user tries to provide an unwieldy number of parameter, I think it's fine to let them and risk running out of memory. As @clalancette  pointed out, the current implementation is not doing any pre-allocation, but bounding the total possible allocations. Does this actually support a real-time use-case (I'm not an expert)? If not, then I vote we simply remove the limits, and in the future we can add opt-in support for the real-time use-case.

**Comment by wjwwood** [comment] 2019-10-18 00:50
@anup-pem it would be great if you could chime in soon so we can potentially resolve this for eloquent. 

Personally I don’t mind removing the limits. I agree they’re doing very little.

**Comment by anup-pem** [comment] 2019-10-21 19:45
@jdlangs @wjwwood Sorry for the delay in my response. As @clalancette mentioned in his response that it is just used for string array bounds. It is OK to bump up the limits or remove the limits if there is a better way to bound the size

**Comment by jacobperron** [comment] 2019-10-21 20:56
I may be wrong, but I'll also point out that these bounds are only currently applying to parameters in YAML files. So, it's still possible for users to violate these limits by passing parameters from the command-line.

**Closed** 2019-10-21 22:21 UTC
Labels: enhancement
